apiVersion: v1
kind: Service
metadata:
  name: my-service
  namespace: dev-namespace
spec:
  ports:
  - name: portname
    port: 80
    protocol: TCP
    targetPort: 80
  - name: sslport
    port: 443
    protocol: TCP
    targetPort: 80
  selector:
    app: my-app
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: my-app
  name: my-deployment
  namespace: dev-namespace
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - image: nginx
        name: my-container
        ports:
        - containerPort: 80
          name: MYAPP
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 100Mi
