apiVersion: v1
kind: Service
metadata:
  annotations:
    our.first.annotation: Fantastic use of annotation!
  labels:
    our-first-common-label: its-everywhere
  name: tfpref-my-service-tfsuf
  namespace: custom-namespace-name
spec:
  ports:
  - name: portname
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: my-app
    our-first-common-label: its-everywhere
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    our.first.annotation: Fantastic use of annotation!
  labels:
    app: my-app
    our-first-common-label: its-everywhere
  name: tfpref-my-deployment-tfsuf
  namespace: custom-namespace-name
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
      our-first-common-label: its-everywhere
  template:
    metadata:
      annotations:
        our.first.annotation: Fantastic use of annotation!
      labels:
        app: my-app
        our-first-common-label: its-everywhere
    spec:
      containers:
      - image: nginx
        name: my-container
        ports:
        - containerPort: 80
          name: MYAPP
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 100Mi
